const KEY="AMIRY_100_STYLES_V2",SITEKEY="AMIRY_SITE_V2";
const names=["کوتاهی کلاسیک","کوتاهی ساده","فید پایین","فید متوسط","فید بالا","فید پوست","کرو کات","باز کات","تکستچر کوتاه","ساید پارت","ساید فید","فید مدرن","فید جوان","مدل اسپرت","مدل رسمی","مدل دانشجویی","مدل روزانه","مدل شیک","مدل خاص","مدل جدید","فید کم","فید تمیز","فید خطی","فید سایه","کوتاهی مرتب","کوتاهی مردانه","مدل اروپایی","مدل کلاسیک ۲","مدل کلاسیک ۳","مدل مدرن ۲","مدل مدرن ۳","مدل جوان","مدل رسمی ۲","مدل اسپرت ۲","مدل اسپرت ۳","مدل کوتاه ۲","مدل کوتاه ۳","مدل خط‌دار","مدل خط‌دار ۲","مدل فید خاص","اصلاح ریش ساده","ریش کوتاه","ریش مرتب","ریش خط‌دار","ریش فید","ریش کلاسیک","ریش بلند","ریش متوسط","ریش کم","ریش حرفه‌ای","ریش مدل ۱۱","ریش مدل ۱۲","ریش مدل ۱۳","ریش مدل ۱۴","ریش مدل ۱۵","ریش مدل ۱۶","ریش مدل ۱۷","ریش مدل ۱۸","ریش مدل ۱۹","ریش مدل ۲۰","اصلاح ریش و مو","مو و ریش کلاسیک","مو و ریش مدرن","مو و ریش اسپرت","مو و ریش رسمی","مو و ریش ویژه","استایل ترکیبی ۱","استایل ترکیبی ۲","استایل ترکیبی ۳","استایل ترکیبی ۴","استایل ترکیبی ۵","استایل ترکیبی ۶","استایل ترکیبی ۷","استایل ترکیبی ۸","استایل ترکیبی ۹","استایل ترکیبی ۱۰","استایل ویژه ۱","استایل ویژه ۲","استایل ویژه ۳","استایل ویژه ۴","استایل داماد ساده","داماد کلاسیک","داماد مدرن","داماد لوکس","داماد ویژه","داماد VIP","داماد طلایی","داماد مجلسی","داماد رسمی","داماد شیک","داماد استایل ۱","داماد استایل ۲","داماد استایل ۳","داماد استایل ۴","داماد استایل ۵","داماد استایل ۶","داماد استایل ۷","داماد استایل ۸","داماد استایل ۹","داماد ویژه VIP"];
function defaults(){return Array.from({length:100},(_,i)=>{let price=Math.min(50+i*30,2700),cat=i>=80?"داماد":i>=40?"ریش و مو":"مو";if(i===99){price=3000;cat="داماد"}return{id:i+1,name:names[i],price:price+" افغانی",category:cat,description:"",image:""}})}
function getProducts(){try{let p=JSON.parse(localStorage.getItem(KEY));return Array.isArray(p)&&p.length===100?p:defaults()}catch{return defaults()}}
let products=getProducts(),editing=false,pendingImage="",site=(()=>{try{return JSON.parse(localStorage.getItem(SITEKEY))||{title:"AMIRY",description:"استایل مورد علاقه‌ات را انتخاب کن."}}catch{return{title:"AMIRY",description:"استایل مورد علاقه‌ات را انتخاب کن."}}})();
const $=s=>document.querySelector(s);function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function ph(id){let s=`<svg xmlns="http://www.w3.org/2000/svg" width="700" height="700"><rect width="100%" height="100%" fill="#e7e7e7"/><text x="50%" y="50%" text-anchor="middle" font-family="Arial" font-size="65" fill="#666">AMIRY ${id}</text></svg>`;return"data:image/svg+xml;charset=UTF-8,"+encodeURIComponent(s)}
function render(){let old=$("#categoryFilter").value;$("#siteTitle").textContent=site.title;$("#siteDescription").textContent=site.description;let cats=[...new Set(products.map(p=>p.category))];$("#categoryFilter").innerHTML='<option value="all">همه</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join("");if(cats.includes(old))$("#categoryFilter").value=old;let q=$("#search").value.toLowerCase(),cat=$("#categoryFilter").value;let list=products.filter(p=>(cat==="all"||p.category===cat)&&(`${p.name} ${p.price} ${p.category}`).toLowerCase().includes(q));$("#products").innerHTML=list.map(p=>`<article class="product"><img class="product-img" src="${p.image||ph(p.id)}" alt="${esc(p.name)}"><div class="product-body"><div class="category">${esc(p.category)}</div><h3>${esc(p.name)}</h3><div class="price">${esc(p.price)}</div><div class="desc">${esc(p.description)}</div><button class="edit-btn" onclick="openEditor(${p.id})">✏️ ویرایش</button></div></article>`).join("");document.body.classList.toggle("editing",editing)}
window.openEditor=id=>{let p=products.find(x=>x.id===id);$("#productId").value=id;$("#editName").value=p.name;$("#editPrice").value=p.price;$("#editCategory").value=p.category;$("#editDescription").value=p.description;pendingImage=p.image||"";$("#editPreview").src=p.image||ph(id);$("#editPreview").style.display="block";$("#productEditor").classList.remove("hidden")};
$("#editImage").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{pendingImage=r.result;$("#editPreview").src=pendingImage};r.readAsDataURL(f)};
$("#saveProduct").onclick=()=>{let p=products.find(x=>x.id===Number($("#productId").value));p.name=$("#editName").value||p.name;p.price=$("#editPrice").value||p.price;p.category=$("#editCategory").value||p.category;p.description=$("#editDescription").value;p.image=pendingImage;localStorage.setItem(KEY,JSON.stringify(products));$("#productEditor").classList.add("hidden");render()};
$("#adminBtn").onclick=()=>{editing=!editing;document.body.classList.toggle("editing",editing);if(editing){$("#editSiteTitle").value=site.title;$("#editSiteDescription").value=site.description;$("#adminPanel").classList.remove("hidden")}};
$("#closeAdmin").onclick=()=>$("#adminPanel").classList.add("hidden");$("#saveSite").onclick=()=>{site={title:$("#editSiteTitle").value||"AMIRY",description:$("#editSiteDescription").value||""};localStorage.setItem(SITEKEY,JSON.stringify(site));$("#adminPanel").classList.add("hidden");render()};$("#closeEditor").onclick=()=>$("#productEditor").classList.add("hidden");$("#search").oninput=render;$("#categoryFilter").onchange=render;render();